
# Use the official Golang image as the base image
FROM golang:1.22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .
COPY .env ./

# Build the Go application
RUN go build -o main .

# Expose the port that the application listens on
EXPOSE 8080

# Command to run the application
CMD ["./main"]
